language: elixir
matrix:

  # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md

  include:

  # Elixir 1.4

  - elixir: 1.4.5
    otp_release: 19.3

  - elixir: 1.4.5
    otp_release: 20.3

  # Elixir 1.5

  - elixir: 1.5.3
    otp_release: 19.3

  - elixir: 1.5.3
    otp_release: 20.3

  # Elixir 1.6

  - elixir: 1.6.6
    otp_release: 19.3

  - elixir: 1.6.6
    otp_release: 20.3

  - elixir: 1.6.6
    otp_release: 21.0

  # Elixir 1.7

  - elixir: 1.7.4
    otp_release: 19.3

  - elixir: 1.7.4
    otp_release: 20.3

  - elixir: 1.7.4
    otp_release: 21.0

  - elixir: 1.7.4
    otp_release: 22.0

  # Elixir 1.8

  - elixir: 1.8.2
    otp_release: 20.3

  - elixir: 1.8.2
    otp_release: 21.0

  - elixir: 1.8.2
    otp_release: 22.0

  # Elixir 1.9

  - elixir: 1.9.0
    otp_release: 20.3

  - elixir: 1.9.0
    otp_release: 21.0

  - elixir: 1.9.0
    otp_release: 22.0

  # Elixir 1.10

  - elixir: 1.10.0
    otp_release: 21.0

  - elixir: 1.10.0
    otp_release: 22.0

  - elixir: 1.10.3
    otp_release: 23.0


env:
- MIX_ENV=test COVERALLS_ELIXIR_VERSION=1.8.2 COVERALLS_OTP_RELEASE=21.0
script:
- mix test
after_script:
- ./coveralls.sh

