name: Elixir CI

on:
  push:
    branches: [ master, update-ci ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-20.04

    # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md
    strategy:
      matrix:
        include:
          #
          # Elixir 1.14
          #
          - elixir: 1.14.0
            otp_release: 23.3.4.9

          - elixir: 1.14.0
            otp_release: 24.2.1

          - elixir: 1.14.0
            otp_release: 25.1.1

          #
          # Elixir 1.15
          #
          - elixir: 1.15.8
            otp_release: 25.3.2.15

          #
          # Elixir 1.16
          #
          - elixir: 1.16.3
            otp_release: 25.3.2.15

          - elixir: 1.16.3
            otp_release: 26.2.5.4

          #
          # Elixir 1.17
          #
          - elixir: 1.17.3
            otp_release: 27.1.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.elixir }}-${{ matrix.otp_release }}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --exclude ssl

  test-ssl:
    # Github Actions environment has unreproducible issues with openssl, libcrypto,
    # Erlang builds, etc. So we run in container to control everything.
    name: Run SSL tests
    runs-on: ubuntu-20.04

    container: elixir
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Install Hex
      run: mix local.hex --force
    - name: Install Rebar
      run: mix local.rebar --force
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --only ssl

  code_quality:
    name: Check or calculate code quality metrics
    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: coveralls-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Send coveralls
      run: mix coveralls.github

