name: Elixir CI

on:
  push:
    branches: [ master, update-ci ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-18.04

    # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md
    strategy:
      matrix:
        include:

          # Elixir 1.9

          - elixir: 1.9.0
            otp_release: 21.3.8.24

          - elixir: 1.9.0
            otp_release: 22.3.4.23

          # Elixir 1.10

          - elixir: 1.10.0
            otp_release: 21.3.8.24

          - elixir: 1.10.0
            otp_release: 22.3.4.23

          - elixir: 1.10.3
            otp_release: 23.3.4.9

          # Elixir 1.11

          - elixir: 1.11.4
            otp_release: 21.3.8.24

          - elixir: 1.11.4
            otp_release: 22.3.4.23

          - elixir: 1.11.4
            otp_release: 23.3.4.9

          - elixir: 1.11.4
            otp_release: 24.1.6

          # Elixir 1.12

          - elixir: 1.12.3
            otp_release: 22.3.4.23

          - elixir: 1.12.3
            otp_release: 23.3.4.9

          - elixir: 1.12.3
            otp_release: 24.1.6

          # Elixir 1.13

          - elixir: 1.13.2
            otp_release: 22.3.4.23

          - elixir: 1.13.2
            otp_release: 23.3.4.9

          - elixir: 1.13.2
            otp_release: 24.2.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.elixir }}-${{ matrix.otp_release }}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --exclude ssl

  test-ssl:
    # Github Actions environment has unreproducible issues with openssl, libcrypto,
    # Erlang builds, etc. So we run in container to control everything.
    name: Run SSL tests
    runs-on: ubuntu-18.04

    container: elixir
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Install Hex
      run: mix local.hex --force
    - name: Install Rebar
      run: mix local.rebar --force
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --only ssl

  code_quality:
    name: Check or calculate code quality metrics
    runs-on: ubuntu-18.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: coveralls-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Send coveralls
      run: mix coveralls.github

