name: Elixir CI

on:
  push:
    branches: [ master, fix-tests ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md
    strategy:
      matrix:
        include:

          # Elixir 1.7

          - elixir: 1.7.4
            otp_release: 21.0

          - elixir: 1.7.4
            otp_release: 22.0

          # Elixir 1.8

          - elixir: 1.8.2
            otp_release: 21.0

          - elixir: 1.8.2
            otp_release: 22.0

          # Elixir 1.9

          - elixir: 1.9.0
            otp_release: 21.0

          - elixir: 1.9.0
            otp_release: 22.0

          # Elixir 1.10

          - elixir: 1.10.0
            otp_release: 21.0

          - elixir: 1.10.0
            otp_release: 22.0

          - elixir: 1.10.3
            otp_release: 23.0

          # Elixir 1.11

          - elixir: 1.11.0
            otp_release: 21.0

          - elixir: 1.11.0
            otp_release: 22.0

          - elixir: 1.11.0
            otp_release: 23.0


    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp_release }} # Define the OTP version [required]
        experimental-otp: true
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.elixir }}-${{ matrix.otp_release }}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --exclude ssl

  test-ssl:
    # Github Actions environment has unreproducible issues with openssl, libcrypto,
    # Erlang builds, etc. So we run in container to control everything.
    name: Run SSL tests
    runs-on: ubuntu-latest
    container: elixir
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Install Hex
      run: mix local.hex --force
    - name: Install Rebar
      run: mix local.rebar --force
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test --only ssl

  code_quality:
    name: Check or calculate code quality metrics
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4' # Define the elixir version [required]
        otp-version: '23.0' # Define the OTP version [required]
        experimental-otp: true
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: coveralls-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Send coveralls
      run: mix coveralls.github

